name: CICD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Set node
       uses: actions/setup-node@v4
       with:
        node-version: 18

     - name: Install Dependiences
       run: npm istall

     - name: Run Test
       run: npm test

     - name: Build Docker Image
       run: docker build -t new-message-app .

     - name: Run Docker Images
       run: docker run -d -p 4013:5013 new-message-app
